
name: Daily Website Check

on:
  schedule:
    - cron: '0 8 * * *'  # runs daily at 8:00 UTC
  workflow_dispatch:  # optional: manual trigger

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install requests
        run: pip install requests
      - name: Run script
        run: python check_substances.py

